### ISSUE TITLE
Wiki - Add info for reverting back to original FW

### ISSUE THREAD

**Issue by halfmanbear** [OpenNeptune3D/OpenNept4une#104]
Steps for reverting back to original FW

**Comment by halfmanbear** [comment]
Complete:

https://github.com/OpenNeptune3D/OpenNept4une/wiki/Reverting-back-to-Original-Elegoo-Firmware-&-Software

**Comment by Rickwo15** [comment]
Please is it possible to add mor detailed manual iam not surre if the MCu must be flashed on open neptune or if it will be automatically installed after putting original image to emmc and powring up the printer. Iam not able to get beck stock firmware

**Comment by halfmanbear** [comment]
It doesn't matter which order you choose to do the steps

https://github.com/OpenNeptune3D/OpenNept4une/wiki/Reverting-back-to-Original-Elegoo-Firmware-&-Software
