### ISSUE TITLE
Screws tilt adjustments does not display values & hints when they in red zone

### ISSUE THREAD

**Issue by fifonik** [OpenNeptune3D/OpenNept4une#106]
Installed it on Neptune 4.
Started the screw tuning and after probing it does not show any hints on screen.
At the beginning I thought everything is good as the bed is aligned (it was aligned before flashing OpenNeptune3D):
![PXL_20240212_104306324](https://github.com/OpenNeptune3D/OpenNept4une/assets/7234987/a75e3be6-0f94-4c26-8308-99231b606591)

Print failed and later I noticed that in web UI it actually shows a popup with red values. Started to tune it up and when reach "green zone" it is displayed on screen.
![PXL_20240212_105729390](https://github.com/OpenNeptune3D/OpenNept4une/assets/7234987/65c5baf1-ddbb-43ca-b5f3-884fd346633c)

So for now it is impossible for me to adjust screws without web UI.

**Comment by Justdigit** [comment]
Do yourself a favor... Get 4 silicone spacers instead of the springs.
Search on YouTube bed leveler 5000.
And be done with it.....

**Comment by fifonik** [comment]
Will it fix the screen's UI? :-P
