### ISSUE TITLE
user_settings.cfg

### ISSUE THREAD

**Issue by chuckkay** [OpenNeptune3D/OpenNept4une#128]
I've noticed that OpenNeptune for Klipper now supports a new file for user custom macros, which is a great addition. However, I have a concern regarding the prioritization of settings in this file compared to the printer.cfg.

For example, if we define a custom [gcode_macro END_TUNE] with a different song in printer.cfg, we would lose it whenever we run an update using ~/OpenNept4une/OpenNept4une.sh. But, if user_settings.cfg had priority, by putting a custom [gcode_macro END_TUNE] in user_settings.cfg, it would remain untouched and override the default END_TUNE. Similarly, if we put: 
[extruder]
nozzle_diameter: 0.8

in user_settings.cfg, it should override the corresponding setting in printer.cfg.

I appreciate all the tweaks you're making to improve the functionality of these printers. However, if we have our own settings we prefer, wouldn't it be better to keep them in a separate file like user_settings.cfg and not interfere with the more critical settings in printer.cfg? Alternatively, if user_settings.cfg cannot be set up to have priority over printer.cfg, then perhaps it could be eliminated, and a file called openneptune.cfg could be created where your updates would go, leaving printer.cfg simpler for the user to customize. I believe this is how other Klipper mods work, like KAMP, where the main code is in KAMP.cfg and any overrides are put in printer.cfg.

**Comment by halfmanbear** [comment]
Thank you for raising this, I've now fixed the behaviour within `dev` branch.

I moved the `[include user_settings.cfg]` to the end of the main body of the printer.cfg (but above SAVE_CONFIG section).

this causes any entries within user_settings.cfg to override duplicate entries within printer.cfg 

<img width="743" alt="Screenshot 2024-02-27 at 23 45 14" src="https://github.com/OpenNeptune3D/OpenNept4une/assets/89969229/44681f68-736e-42ea-8cfc-6ff7f9724853">
