### ISSUE TITLE
FYI Mainsail.cfg & fluid.cfg are not in sync

### ISSUE THREAD

**Issue by chuckkay** [OpenNeptune3D/OpenNept4une#129]
a few differences between the two files
ie line 79-80 one says Pause the other Resume

and fluid.cfg has a few more sections of definitions and code

not sure if these differences are  because of the way the 2 GUI's operate or if the cfg files are just not synced up..

**Comment by halfmanbear** [comment]
They aren't generated by us, they are provided with each web UI install. All of these macros get overridden by anything below in the printer.cfg
