### ISSUE TITLE
Left Screws Adjustment Results Missing from Klipperscreen

### ISSUE THREAD

**Issue by thestip** [OpenNeptune3D/OpenNept4une#137]
The macro checks all 4 spots but the display (Klipperscreen) only shows the adjustments needed for the 2 right screws. The 2 left screws only have the default icon showing. All 4 adjustments are listed in the console.

**Comment by halfmanbear** [comment]
We are currently only working on support for the elegoo touchscreen.

I'm not sure how klipperscreen works I think that would be an issue to raise with them directly? 

https://github.com/KlipperScreen/KlipperScreen
