### ISSUE TITLE
Not working Klipper

### ISSUE THREAD

**Issue by Fapi097** [OpenNeptune3D/OpenNept4une#145]
hello i have the problem klipper will not start
![Uploading Bild_2024-03-12_213741050.png…]()

**Comment by Fapi097** [comment]
![Bild_2024-03-12_213828255](https://github.com/OpenNeptune3D/OpenNept4une/assets/126707665/940fc701-3def-47ae-87eb-541fbd49bcec)

**Comment by halfmanbear** [comment]
Log in via SSH as mks

`rm -rf ~/OpenNept4une`

`cd ~/ && git clone https://github.com/OpenNeptune3D/OpenNept4une.git`

**Comment by Fapi097** [comment]
Thank you a lot halfmanbear i Test it out
