### ISSUE TITLE
Cannot add config to Orca

### ISSUE THREAD

**Issue by rashevskyv** [OpenNeptune3D/OpenNept4une#146]
Using version OrcaSlicer V2.0.0 Beta Release

File -> Import -> Import configs -> Elegoo Neptune 4 (0.4 nozzle)-OpenNept4une.orca_printer

![изображение](https://github.com/OpenNeptune3D/OpenNept4une/assets/18294541/d36e3e10-e125-439b-ac5c-f56021e78b5a)

I have already 4 printers on orca's config, include vanilla N4. Please help me add OpenNept4une's config

**Comment by halfmanbear** [comment]
Have you already set up orcas default profiles for the N4 first as per

https://github.com/OpenNeptune3D/OpenNept4une/wiki#importing-orcaslicer-profiles

Does this work in the non beta latest release orcaalicer version as suggested?

**Comment by Kemar0611** [comment]
I did the same thing. 
![image](https://github.com/OpenNeptune3D/OpenNept4une/assets/31227996/a0e823a2-e5c1-4079-bd71-2c2e54bd6b93)
![image](https://github.com/OpenNeptune3D/OpenNept4une/assets/31227996/5df02977-5215-4fa8-a96c-4957b874e037)
