### ISSUE TITLE
Minor typo in OpenNept4une.sh

### ISSUE THREAD

**Issue by Ataraxia-Mechanica** [OpenNeptune3D/OpenNept4une#158]
![bruh](https://github.com/OpenNeptune3D/OpenNept4une/assets/111327195/c7449a7a-63fa-4908-a791-3ea127a09ff0)
literally unusable

**Comment by halfmanbear** [comment]
Fixed in dev cheers!
https://github.com/OpenNeptune3D/OpenNept4une/commit/a3ef436113de08a73edf458da08c3d87b0132d3c
