### ISSUE TITLE
g28 does not always go to endstops

### ISSUE THREAD

**Issue by RuthlessTX** [OpenNeptune3D/OpenNept4une#170]
v0.1.5-541-g9bc975aa - G28 ignores Y position randomly and crashes outside of bed
g90, g28 then BED_LEVEL_SCREWS_TUNE works manually but not in scripting

**Comment by RuthlessTX** [comment]
![image](https://github.com/OpenNeptune3D/OpenNept4une/assets/166194954/40ff66b9-c3c9-41c0-896f-557c88183b64)

Needed to update my settings in the Printer.cfg file - defaults were way off

**Comment by LoQue90** [comment]
Oh, did had the same issue.
That was the point where my probe and z_offset, nozzle into pei sheet crashed begun.
