### ISSUE TITLE
Bring back base reference printer.cfg configs?

### ISSUE THREAD

**Issue by jKawka-ITV** [OpenNeptune3D/OpenNept4une#173]
I understand the ease-of-development reasoning behind splitting the confs into a bunch of separate files for each printer and running a script that combines them with a baseline skeleton to make a printer.cfg specific to each model, but would it be possible to include the final output in the repo again?

I've modified my NP4 config a decent amount so it was quite nice being able to just pull the repo, grab the updated file and do a diff between the two to sift between my existing changes and any new changes to the config that I may want to copy over.

**Comment by halfmanbear** [comment]
I'm reluctant to have to compile and upload 6 printer.cfgs whenever make any edits.

Although in the process of implementing a diff check before the user confirms the cfg update.

For now you can run the below and change `n4plus` with either `n4` , `n4pro` or `n4max`.

```
python3 ~/OpenNept4une/printer-confs/generate_conf.py n4plus && diff ~/OpenNept4une/printer-confs/output.cfg ~/printer_data/config/printer.cfg
```
