### ISSUE TITLE
Default theme gone

### ISSUE THREAD

**Issue by callimburg** [OpenNeptune3D/OpenNept4une#183]
So, I've changed the theme for the fluidd interface and when I wanted to use the default one it wasn't there anymore, is it normal? I just wanted to see the others but the default was the best in the end.

**Comment by halfmanbear** [comment]
the way we push the theme is via fluidds database file, you'll have to run `opennept4une` then select option 1 and update printer.cfg and click yes on updating other configs. although this will reset fluid / crowsnest etc to our shipped config.

**Comment by callimburg** [comment]
Thanks, I'll keep the fluidd one on until when I'll feel like reinstalling it then!
