### ISSUE TITLE
Cancelling Print causes crash

### ISSUE THREAD

**Issue by mwelby** [OpenNeptune3D/OpenNept4une#185]
Hi on the Neptune Pro 4 - the firmware crashes if you try and cancel a print.

I have tried both in the Klipper interface and on the touchscreen and both exhibit the same issue.

If you need logs or further info, please let me know.

**Comment by halfmanbear** [comment]
If you issue `CANCEL_PRINT` the print should finish the buffered gcode then issue a print end (early). 

The red (emergency) stop button (M112) should cause an immediate print cancel causing klipper firmware to shutdown, requiring a manual firmware restart.

So when you are issuing `CANCEL_PRINT` is it crashing or stopping firmware? Klipper's firmware? Or the touchscreen display firmware?

**Comment by mwelby** [comment]
Hi,

I am guessing I am probably not waiting for the buffer to clear - how long is the buffer?

The emergency stop works instantly.

The only one that seems ages is in klipper and the touchscreen (Cancel)

**Comment by phillipthelen** [comment]
I'm not entirely sure what you describing.
Using the button to Stop from the display or fluidd is not immediate, that is correct. As @halfmanbear described the buffered gcode is executed first.

Where exactly are you seeing the crash and what is the error message?

**Comment by mwelby** [comment]
Please ignore this - I think it's just me being impatient while the buffer clears and then stops the print.
