### ISSUE TITLE
shaper_calibrate N4Max

### ISSUE THREAD

**Issue by wjflier** [OpenNeptune3D/OpenNept4une#187]
I'm getting this error message when I try to run SHAPER_CALIBRATE "Invalid adxl345 id (got 0 vs e5).
This is generally indicative of connection problems
(e.g. faulty wiring) or a faulty adxl345 chip."

**Comment by NoodleMan171** [comment]
you have to find the cs pin for your accelerometer, i looked on the amazon page for the one i bought and they had some configuration examples that showed the pin they used, ended up working for mine
