### ISSUE TITLE
At end of print noozle starts going down smashing into the print

### ISSUE THREAD

**Issue by Sulginger** [OpenNeptune3D/OpenNept4une#194]
Hey, at the end of my prints since switching to OpenNept4une the noozle starts going down straight into the print destorying it for some season.
I tried adding G1 Z10 into the "PRINT_END" command but it changes nothing, anyone got a solution for me please? Its kinda frustrating  :(

**Comment by halfmanbear** [comment]
Can you upload your printer.cfg and screenshot the machine gcode from the slicer profile your using

**Comment by halfmanbear** [comment]
Hmm there is nothing there with a downward z move. Anything show in the klipper console?

**Comment by Sulginger** [comment]
No not rly anything sus

**Comment by Sulginger** [comment]
Do you have any PRINT_END gCode which works? I'd just copy that and paste it into my printer.cfg

**Comment by lexxxel** [comment]
> Ficked it by updating and installing the whole thing new

Can this issue then be closed?
