### ISSUE TITLE
Wifi

### ISSUE THREAD

**Issue by john270** [OpenNeptune3D/OpenNept4une#195]
Hi,
I've set up my N4pro today, thanks for super walkthrough instructions :-)
One thing that's left me confused is the WiFi setup, does the printer have built in WiFi capabilities or does it still require a usb dongle?
Thanks

**Comment by phillipthelen** [comment]
The Neptune 4 and 4 pro do not have built in wifi and need to be connected with either an Ethernet cable or a wifi usb Stick.
