### ISSUE TITLE
Neptune 4 max Untracked Source Files

### ISSUE THREAD

**Issue by BiggumBuddha** [OpenNeptune3D/OpenNept4une#196]
I've gotten this notification in my neptune 4 max, but I don't have it in my N4basic.

`Repo has untracked source files: ['klippy/extras/gcode_shell_command.py']`

Any insight to what is going on?

**Comment by halfmanbear** [comment]
This was a plugin via kiauh for controlling the frame lights. It's no longer required so the file can be deleted with.

```
sudo rm ~/klippy/extras/gcode_shell_command.py
```
