### ISSUE TITLE
4 Max not printing just hanging after adaptive bed mesh and set temp

### ISSUE THREAD

**Issue by BiggumBuddha** [OpenNeptune3D/OpenNept4une#198]
Recently updated (within the last week) and i've run into an issue where my Max will go through the adaptive, park and wait for the temps to reach......and just stay there. I'm running Orca 6.1.1, klipper v0.12.0-263-g0087f04c and OpenNept4une v0.1.5-544-ge43fb93f. I've also updated all of the base OS linux packages as well with no change.

Short of reflashing the eMMC (which is about where i'm at), any suggestions? I also did just replace the hotbed, but not sure if that is relevant. I've attached the klipper log for additional data.
[klippy.log](https://github.com/user-attachments/files/16188772/klippy.log)

**Comment by halfmanbear** [comment]
Have you tried updating your `printer.cfg` within `opennept4une` script option `1`?
