### ISSUE TITLE
Error: Option 'pin' is not valid in section 'gcode_macro part_light_off'

### ISSUE THREAD

**Issue by BiggumBuddha** [OpenNeptune3D/OpenNept4une#200]
Reflashed and updated my N4Max and this gem popped up after reboot. 
![Screenshot 2024-07-15 171413](https://github.com/user-attachments/assets/8ff1b813-ea6a-4464-bcf4-a71b2ec1f20f)

**Comment by BiggumBuddha** [comment]
Here's an grab from my current printer.cfg:
![Screenshot 2024-07-15 171706](https://github.com/user-attachments/assets/df412e26-a35f-4f63-8ab5-4028afd52ed5)

**Comment by halfmanbear** [comment]
Have you installed/updated the virtual MCU within `opennept4une` menu option 4?

**Comment by BiggumBuddha** [comment]
I did. I just ran through it with the same outcome.

**Comment by BiggumBuddha** [comment]
@halfmanbear On a whim, I deleted the generated printer.cfg and recreated it through the opennept4une shell, and it worked correctly. I'll go ahead and close this issue.
