### ISSUE TITLE
Error after put personal config in user_settings.cfg

### ISSUE THREAD

**Issue by ygarand** [OpenNeptune3D/OpenNept4une#219]
Hi,  

I add this config into my user_settings.cfg this personal config

[extruder]
rotation_distance: 28.5483695616              ; 31.4 Bondtech 5mm Drive Gears

and after I click save and resart I receives this error in FLUIDD do you know what is cause this error.

<img width="836" alt="image" src="https://github.com/user-attachments/assets/8990f506-cb17-46c7-9100-30a7a61dcd44">

Thanks

**Comment by halfmanbear** [comment]
Try using only one decimal place?

**Comment by ygarand** [comment]
I already try and is same thing.

**Comment by halfmanbear** [comment]
This works for me in `user_settings.cfg`

```
[extruder]
rotation_distance: 28.548
```

**Comment by ygarand** [comment]
I try your setting and is not working for me.
