### ISSUE TITLE
Klipper LCD interface

### ISSUE THREAD

**Issue by barthemb** [OpenNeptune3D/OpenNept4une#232]
Hello, is it possible to have klipperscreen classic on the LCD screen? I don't really like the Neptune interface

**Comment by halfmanbear** [comment]
Hello! Unfortunately, the TJC screen that comes with the printer isn’t compatible with KlipperScreen. However, you can easily use a spare or old Android phone or tablet as an alternative.

Another great option is the Moonraker app, which provides a convenient wireless solution.
