### ISSUE TITLE
Suggested Instructions clarification 

### ISSUE THREAD

**Issue by chuckkay** [OpenNeptune3D/OpenNept4une#63]
Step 2 Flash your eMMC with the latest OpenNept4une release image.   Missing any information on how to do this, i used raspberry pi image software, and winged it. Others might not be so lucky, also a link to something other then Aliexpress explaining how to remove old emmc chip proper attachment to usb adapter etx

**Comment by chuckkay** [comment]
actually i re-read it, you do have the name of the program to use to flash emmc, just no link... i missed it..

**Comment by halfmanbear** [comment]
I've added a link to https://etcher.balena.io/ in the readme.md (in dev for now)
