### ISSUE TITLE
pause on runout...

### ISSUE THREAD

**Issue by chuckkay** [OpenNeptune3D/OpenNept4une#73]
I dont understand something, the Pause on filament runout is working fine, the print pauses for me to reload filament, but the strange thing is i was looking at printer.cfg file and i see Filament Sensor section Pause on runout is set to false, how is that possible it's set to false but it's still doing it's job..

#####################################################################
# Filament sensor
#####################################################################

[filament_switch_sensor fila]
pause_on_runout: False
runout_gcode:
            M600
insert_gcode:
event_delay: 3.0
pause_delay: 1.0
switch_pin: PA12

**Comment by halfmanbear** [comment]
Because I don't want it to preform a normal PAUSE action straight away. I've got it to trigger my M600 instead. The M600 has the pause function call within it so ultimately it does pause even though it says false.

**Comment by chuckkay** [comment]
ok thanks,
maybe a #comment line "do not touch", 🤓as people gonna monkey around.
