### ISSUE TITLE
front USB-C port - can it be enabled and be used

### ISSUE THREAD

**Issue by chuckkay** [OpenNeptune3D/OpenNept4une#74]
i read somewhere at the front USB-C port is for internal use by the manufacturer and not usable as standard USB, was wondering if the port could be enabled and used,  and if it provides enough power  for a big tree tech LCD screen for Klipper screen

**Comment by plygrnd** [comment]
![Screenshot_20240203-112453.png](https://github.com/OpenNeptune3D/OpenNept4une/assets/21295236/e8f42cab-12bb-49b0-b828-26c1302255ed)

In the above picture, the USB-C port (labeled HUS) is wired directly into the [CH340C](https://wch-ic.com/products/CH340.html) USB bus converter above it ([source](https://r6e.github.io/neptune_4/hardware.html))

**Comment by halfmanbear** [comment]
Yes its for the serial terminal connection. It is enabled and you can use it for this purpose.
