### ISSUE TITLE
Display stops updating when probing bed before print start

### ISSUE THREAD

**Issue by scherlund** [OpenNeptune3D/OpenNept4une#85]
When a print is started the screen stops updating when adaptive meshing starts.

The screen doesn't freeze as the little animations for the bed temp and Fan still moves, but no new information is shown.

This is using the latest OpenNept4une and Display connector (Stable) is of 10 minutes ago. Both updated through the script.

Klipper and everything else is updated through KIAUH.

It is possible to manipulate other thing through the screen while printing like the LEDs. However the button doesn't change. But that could be a separate issue (It's BETA after all)

Attached is a picture of a print in progress (Temp Tower).
![20240208_112731_small](https://github.com/OpenNeptune3D/OpenNept4une/assets/13279853/9a2fd92c-e6a5-46de-82d9-ebca6da7c116)

**Comment by phillipthelen** [comment]
Fixed in both dev and main branch. Updating through Fluidd or OpenNept4une.sh should fix everything :)

**Comment by scherlund** [comment]
Can confirm. With an update it works. It even shows the probing progress now :)

You guys rock.

**Comment by Justdigit** [comment]
Off topic question.... Why you are updating via Kiauh?? And not within fluidd?? Is. That different? Or beteer?

**Comment by scherlund** [comment]
> Off topic question.... Why you are updating via Kiauh?? And not within fluidd?? Is. That different? Or beteer?

Neither worse nor better :) 

It's just a personal preference. I like to SSH when doing updates and stuff like that. I use Fluidd/Mainsail for normal printing :)

**Comment by Justdigit** [comment]
> > Off topic question.... Why you are updating via Kiauh?? And not within fluidd?? Is. That different? Or beteer?
> 
> Neither worse nor better :)
> 
> It's just a personal preference. I like to SSH when doing updates and stuff like that. I use Fluidd/Mainsail for normal printing :)

OK thanks for the quick answer.
